// Code generated by Kitex v0.10.0. DO NOT EDIT.

package diskbackservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	disk_back "github.com/cutejiuges/disk_back/kitex_gen/disk_back"
	disk_common "github.com/cutejiuges/disk_back/kitex_gen/disk_common"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Ping(ctx context.Context, req *disk_common.PingRequest, callOptions ...callopt.Option) (r *disk_common.PingResponse, err error)
	UploadFile(ctx context.Context, req *disk_back.UploadFileRequest, callOptions ...callopt.Option) (r *disk_back.UploadFileResponse, err error)
	QueryFileInfo(ctx context.Context, req *disk_common.QueryFileInfoRequest, callOptions ...callopt.Option) (r *disk_back.QueryFileInfoResponse, err error)
	DownloadFile(ctx context.Context, req *disk_common.DownloadFileRequest, callOptions ...callopt.Option) (r *disk_back.DownloadFileResponse, err error)
	EditFileInfo(ctx context.Context, req *disk_common.EditFileInfoRequest, callOptions ...callopt.Option) (r *disk_back.EditFileInfoResponse, err error)
	DeleteFile(ctx context.Context, req *disk_common.DeleteFileRequest, callOptions ...callopt.Option) (r *disk_back.DeleteFileResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kDiskBackServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kDiskBackServiceClient struct {
	*kClient
}

func (p *kDiskBackServiceClient) Ping(ctx context.Context, req *disk_common.PingRequest, callOptions ...callopt.Option) (r *disk_common.PingResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Ping(ctx, req)
}

func (p *kDiskBackServiceClient) UploadFile(ctx context.Context, req *disk_back.UploadFileRequest, callOptions ...callopt.Option) (r *disk_back.UploadFileResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UploadFile(ctx, req)
}

func (p *kDiskBackServiceClient) QueryFileInfo(ctx context.Context, req *disk_common.QueryFileInfoRequest, callOptions ...callopt.Option) (r *disk_back.QueryFileInfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryFileInfo(ctx, req)
}

func (p *kDiskBackServiceClient) DownloadFile(ctx context.Context, req *disk_common.DownloadFileRequest, callOptions ...callopt.Option) (r *disk_back.DownloadFileResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DownloadFile(ctx, req)
}

func (p *kDiskBackServiceClient) EditFileInfo(ctx context.Context, req *disk_common.EditFileInfoRequest, callOptions ...callopt.Option) (r *disk_back.EditFileInfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EditFileInfo(ctx, req)
}

func (p *kDiskBackServiceClient) DeleteFile(ctx context.Context, req *disk_common.DeleteFileRequest, callOptions ...callopt.Option) (r *disk_back.DeleteFileResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteFile(ctx, req)
}
