// Code generated by Kitex v0.10.0. DO NOT EDIT.

package diskbackservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	disk_back "github.com/cutejiuges/disk_back/kitex_gen/disk_back"
	disk_common "github.com/cutejiuges/disk_back/kitex_gen/disk_common"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Ping": kitex.NewMethodInfo(
		pingHandler,
		newDiskBackServicePingArgs,
		newDiskBackServicePingResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UploadFile": kitex.NewMethodInfo(
		uploadFileHandler,
		newDiskBackServiceUploadFileArgs,
		newDiskBackServiceUploadFileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryFileInfo": kitex.NewMethodInfo(
		queryFileInfoHandler,
		newDiskBackServiceQueryFileInfoArgs,
		newDiskBackServiceQueryFileInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DownloadFile": kitex.NewMethodInfo(
		downloadFileHandler,
		newDiskBackServiceDownloadFileArgs,
		newDiskBackServiceDownloadFileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"EditFileInfo": kitex.NewMethodInfo(
		editFileInfoHandler,
		newDiskBackServiceEditFileInfoArgs,
		newDiskBackServiceEditFileInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteFile": kitex.NewMethodInfo(
		deleteFileHandler,
		newDiskBackServiceDeleteFileArgs,
		newDiskBackServiceDeleteFileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	diskBackServiceServiceInfo                = NewServiceInfo()
	diskBackServiceServiceInfoForClient       = NewServiceInfoForClient()
	diskBackServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return diskBackServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return diskBackServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return diskBackServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "DiskBackService"
	handlerType := (*disk_back.DiskBackService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "disk_back",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.10.0",
		Extra:           extra,
	}
	return svcInfo
}

func pingHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*disk_back.DiskBackServicePingArgs)
	realResult := result.(*disk_back.DiskBackServicePingResult)
	success, err := handler.(disk_back.DiskBackService).Ping(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDiskBackServicePingArgs() interface{} {
	return disk_back.NewDiskBackServicePingArgs()
}

func newDiskBackServicePingResult() interface{} {
	return disk_back.NewDiskBackServicePingResult()
}

func uploadFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*disk_back.DiskBackServiceUploadFileArgs)
	realResult := result.(*disk_back.DiskBackServiceUploadFileResult)
	success, err := handler.(disk_back.DiskBackService).UploadFile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDiskBackServiceUploadFileArgs() interface{} {
	return disk_back.NewDiskBackServiceUploadFileArgs()
}

func newDiskBackServiceUploadFileResult() interface{} {
	return disk_back.NewDiskBackServiceUploadFileResult()
}

func queryFileInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*disk_back.DiskBackServiceQueryFileInfoArgs)
	realResult := result.(*disk_back.DiskBackServiceQueryFileInfoResult)
	success, err := handler.(disk_back.DiskBackService).QueryFileInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDiskBackServiceQueryFileInfoArgs() interface{} {
	return disk_back.NewDiskBackServiceQueryFileInfoArgs()
}

func newDiskBackServiceQueryFileInfoResult() interface{} {
	return disk_back.NewDiskBackServiceQueryFileInfoResult()
}

func downloadFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*disk_back.DiskBackServiceDownloadFileArgs)
	realResult := result.(*disk_back.DiskBackServiceDownloadFileResult)
	success, err := handler.(disk_back.DiskBackService).DownloadFile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDiskBackServiceDownloadFileArgs() interface{} {
	return disk_back.NewDiskBackServiceDownloadFileArgs()
}

func newDiskBackServiceDownloadFileResult() interface{} {
	return disk_back.NewDiskBackServiceDownloadFileResult()
}

func editFileInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*disk_back.DiskBackServiceEditFileInfoArgs)
	realResult := result.(*disk_back.DiskBackServiceEditFileInfoResult)
	success, err := handler.(disk_back.DiskBackService).EditFileInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDiskBackServiceEditFileInfoArgs() interface{} {
	return disk_back.NewDiskBackServiceEditFileInfoArgs()
}

func newDiskBackServiceEditFileInfoResult() interface{} {
	return disk_back.NewDiskBackServiceEditFileInfoResult()
}

func deleteFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*disk_back.DiskBackServiceDeleteFileArgs)
	realResult := result.(*disk_back.DiskBackServiceDeleteFileResult)
	success, err := handler.(disk_back.DiskBackService).DeleteFile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDiskBackServiceDeleteFileArgs() interface{} {
	return disk_back.NewDiskBackServiceDeleteFileArgs()
}

func newDiskBackServiceDeleteFileResult() interface{} {
	return disk_back.NewDiskBackServiceDeleteFileResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Ping(ctx context.Context, req *disk_common.PingRequest) (r *disk_common.PingResponse, err error) {
	var _args disk_back.DiskBackServicePingArgs
	_args.Req = req
	var _result disk_back.DiskBackServicePingResult
	if err = p.c.Call(ctx, "Ping", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UploadFile(ctx context.Context, req *disk_back.UploadFileRequest) (r *disk_back.UploadFileResponse, err error) {
	var _args disk_back.DiskBackServiceUploadFileArgs
	_args.Req = req
	var _result disk_back.DiskBackServiceUploadFileResult
	if err = p.c.Call(ctx, "UploadFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryFileInfo(ctx context.Context, req *disk_common.QueryFileInfoRequest) (r *disk_back.QueryFileInfoResponse, err error) {
	var _args disk_back.DiskBackServiceQueryFileInfoArgs
	_args.Req = req
	var _result disk_back.DiskBackServiceQueryFileInfoResult
	if err = p.c.Call(ctx, "QueryFileInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DownloadFile(ctx context.Context, req *disk_common.DownloadFileRequest) (r *disk_back.DownloadFileResponse, err error) {
	var _args disk_back.DiskBackServiceDownloadFileArgs
	_args.Req = req
	var _result disk_back.DiskBackServiceDownloadFileResult
	if err = p.c.Call(ctx, "DownloadFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) EditFileInfo(ctx context.Context, req *disk_common.EditFileInfoRequest) (r *disk_back.EditFileInfoResponse, err error) {
	var _args disk_back.DiskBackServiceEditFileInfoArgs
	_args.Req = req
	var _result disk_back.DiskBackServiceEditFileInfoResult
	if err = p.c.Call(ctx, "EditFileInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteFile(ctx context.Context, req *disk_common.DeleteFileRequest) (r *disk_back.DeleteFileResponse, err error) {
	var _args disk_back.DiskBackServiceDeleteFileArgs
	_args.Req = req
	var _result disk_back.DiskBackServiceDeleteFileResult
	if err = p.c.Call(ctx, "DeleteFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
