// Code generated by hertz generator.

package disk_api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _echoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadfileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryfileinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletefileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _downloadfileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _editfileinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}
