// Code generated by hertz generator.

package disk_api

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	disk_api "github.com/cutejiuges/disk_api/biz/model/disk_api"
	file_server "github.com/cutejiuges/disk_api/biz/model/file_server"
	user_server "github.com/cutejiuges/disk_api/biz/model/user_server"
	file_service "github.com/cutejiuges/disk_api/biz/service/file"
	user_service "github.com/cutejiuges/disk_api/biz/service/user"
	"github.com/cutejiuges/disk_api/infra/localutils"
)

// QueryFileInfo .
// @router file/queryFileInfo [POST]
func QueryFileInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req file_server.QueryFileInfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := file_service.ProcessQueryFileInfo(ctx, &req)
	localutils.Wrapper(c, resp, err)
}

// DownloadFile .
// @router file/downloadFile [GET]
func DownloadFile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req file_server.DownloadFileRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := file_service.ProcessDownloadFile(ctx, &req)
	localutils.Wrapper(c, resp, err)
}

// DeleteFile .
// @router file/deleteFile [POST]
func DeleteFile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req file_server.DeleteFileRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := file_service.ProcessDeleteFile(ctx, &req)
	localutils.Wrapper(c, resp, err)
}

// UploadFileBatch .
// @router /file/uploadFileBatch [POST]
func UploadFileBatch(ctx context.Context, c *app.RequestContext) {
	var err error
	var req disk_api.BlankRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := file_service.ProcessUploadFileBatch(ctx, c, &req)
	localutils.Wrapper(c, resp, err)
}

// GetEmailVerifyCode .
// @router user/getEmailVerifyCode [POST]
func GetEmailVerifyCode(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user_server.GetEmailVerifyCodeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := user_service.ProcessGetEmailVerifyCode(ctx, &req)
	localutils.Wrapper(c, resp, err)
}
