// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "tb_user"

// User 存储用户信息
type User struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:用户id" json:"id"`                            // 用户id
	UserName   string    `gorm:"column:user_name;type:varchar(64);not null;comment:用户昵称" json:"user_name"`                              // 用户昵称
	Password   string    `gorm:"column:password;type:varchar(256);not null;comment:加盐的用户密码" json:"password"`                            // 加盐的用户密码
	Email      string    `gorm:"column:email;type:varchar(128);not null;comment:用户绑定的邮箱" json:"email"`                                  // 用户绑定的邮箱
	Phone      string    `gorm:"column:phone;type:varchar(128);comment:绑定的手机号" json:"phone"`                                            // 绑定的手机号
	Profile    string    `gorm:"column:profile;type:text;comment:用户属性" json:"profile"`                                                  // 用户属性
	Status     int8      `gorm:"column:status;type:tinyint;not null;comment:账户状态" json:"status"`                                        // 账户状态
	SignTime   time.Time `gorm:"column:sign_time;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:账户注册时间" json:"sign_time"`     // 账户注册时间
	LastActive time.Time `gorm:"column:last_active;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:最晚活跃时间" json:"last_active"` // 最晚活跃时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
