// Code generated by Kitex v0.10.0. DO NOT EDIT.

package diskbackservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	disk_common "github.com/cutejiuges/disk_back/kitex_gen/disk_common"
	file_server "github.com/cutejiuges/disk_back/kitex_gen/file_server"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"UploadFile": kitex.NewMethodInfo(
		uploadFileHandler,
		newDiskBackServiceUploadFileArgs,
		newDiskBackServiceUploadFileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryFileInfo": kitex.NewMethodInfo(
		queryFileInfoHandler,
		newDiskBackServiceQueryFileInfoArgs,
		newDiskBackServiceQueryFileInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DownloadFile": kitex.NewMethodInfo(
		downloadFileHandler,
		newDiskBackServiceDownloadFileArgs,
		newDiskBackServiceDownloadFileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"EditFileInfo": kitex.NewMethodInfo(
		editFileInfoHandler,
		newDiskBackServiceEditFileInfoArgs,
		newDiskBackServiceEditFileInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteFile": kitex.NewMethodInfo(
		deleteFileHandler,
		newDiskBackServiceDeleteFileArgs,
		newDiskBackServiceDeleteFileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	diskBackServiceServiceInfo                = NewServiceInfo()
	diskBackServiceServiceInfoForClient       = NewServiceInfoForClient()
	diskBackServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return diskBackServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return diskBackServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return diskBackServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "DiskBackService"
	handlerType := (*file_server.DiskBackService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "file_server",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.10.0",
		Extra:           extra,
	}
	return svcInfo
}

func uploadFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*file_server.DiskBackServiceUploadFileArgs)
	realResult := result.(*file_server.DiskBackServiceUploadFileResult)
	success, err := handler.(file_server.DiskBackService).UploadFile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDiskBackServiceUploadFileArgs() interface{} {
	return file_server.NewDiskBackServiceUploadFileArgs()
}

func newDiskBackServiceUploadFileResult() interface{} {
	return file_server.NewDiskBackServiceUploadFileResult()
}

func queryFileInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*file_server.DiskBackServiceQueryFileInfoArgs)
	realResult := result.(*file_server.DiskBackServiceQueryFileInfoResult)
	success, err := handler.(file_server.DiskBackService).QueryFileInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDiskBackServiceQueryFileInfoArgs() interface{} {
	return file_server.NewDiskBackServiceQueryFileInfoArgs()
}

func newDiskBackServiceQueryFileInfoResult() interface{} {
	return file_server.NewDiskBackServiceQueryFileInfoResult()
}

func downloadFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*file_server.DiskBackServiceDownloadFileArgs)
	realResult := result.(*file_server.DiskBackServiceDownloadFileResult)
	success, err := handler.(file_server.DiskBackService).DownloadFile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDiskBackServiceDownloadFileArgs() interface{} {
	return file_server.NewDiskBackServiceDownloadFileArgs()
}

func newDiskBackServiceDownloadFileResult() interface{} {
	return file_server.NewDiskBackServiceDownloadFileResult()
}

func editFileInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*file_server.DiskBackServiceEditFileInfoArgs)
	realResult := result.(*file_server.DiskBackServiceEditFileInfoResult)
	success, err := handler.(file_server.DiskBackService).EditFileInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDiskBackServiceEditFileInfoArgs() interface{} {
	return file_server.NewDiskBackServiceEditFileInfoArgs()
}

func newDiskBackServiceEditFileInfoResult() interface{} {
	return file_server.NewDiskBackServiceEditFileInfoResult()
}

func deleteFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*file_server.DiskBackServiceDeleteFileArgs)
	realResult := result.(*file_server.DiskBackServiceDeleteFileResult)
	success, err := handler.(file_server.DiskBackService).DeleteFile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDiskBackServiceDeleteFileArgs() interface{} {
	return file_server.NewDiskBackServiceDeleteFileArgs()
}

func newDiskBackServiceDeleteFileResult() interface{} {
	return file_server.NewDiskBackServiceDeleteFileResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) UploadFile(ctx context.Context, req *file_server.UploadFileRequest) (r *file_server.UploadFileResponse, err error) {
	var _args file_server.DiskBackServiceUploadFileArgs
	_args.Req = req
	var _result file_server.DiskBackServiceUploadFileResult
	if err = p.c.Call(ctx, "UploadFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryFileInfo(ctx context.Context, req *disk_common.QueryFileInfoRequest) (r *file_server.QueryFileInfoResponse, err error) {
	var _args file_server.DiskBackServiceQueryFileInfoArgs
	_args.Req = req
	var _result file_server.DiskBackServiceQueryFileInfoResult
	if err = p.c.Call(ctx, "QueryFileInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DownloadFile(ctx context.Context, req *disk_common.DownloadFileRequest) (r *file_server.DownloadFileResponse, err error) {
	var _args file_server.DiskBackServiceDownloadFileArgs
	_args.Req = req
	var _result file_server.DiskBackServiceDownloadFileResult
	if err = p.c.Call(ctx, "DownloadFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) EditFileInfo(ctx context.Context, req *disk_common.EditFileInfoRequest) (r *file_server.EditFileInfoResponse, err error) {
	var _args file_server.DiskBackServiceEditFileInfoArgs
	_args.Req = req
	var _result file_server.DiskBackServiceEditFileInfoResult
	if err = p.c.Call(ctx, "EditFileInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteFile(ctx context.Context, req *disk_common.DeleteFileRequest) (r *file_server.DeleteFileResponse, err error) {
	var _args file_server.DiskBackServiceDeleteFileArgs
	_args.Req = req
	var _result file_server.DiskBackServiceDeleteFileResult
	if err = p.c.Call(ctx, "DeleteFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
