// Code generated by Kitex v0.10.0. DO NOT EDIT.

package diskbackservice

import (
	server "github.com/cloudwego/kitex/server"
	file_server "github.com/cutejiuges/disk_back/kitex_gen/file_server"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler file_server.DiskBackService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
